name: Quick Update Index

concurrency:
  group: github-pages-deploy
  cancel-in-progress: true  # Tự hủy job cũ nếu job mới chạy đè lên

on:
  schedule:
    # Chạy mỗi 15 phút từ 02:00 UTC đến 08:00 UTC (Tương đương 09:00 AM - 15:00 PM GMT+7), T2-T6
    - cron: '*/15 2-8 * * 1-5'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-index:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip' # Tối ưu tốc độ cài thư viện

      - name: Install dependencies
        run: pip install requests pandas beautifulsoup4 plotly user_agent openpyxl kaleido pytz

      - name: Run Scripts
        run: |
          echo "Kích hoạt cập nhật dữ liệu thị trường..."
          python main.py
          python update_index_only.py

          
      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Thêm các file cần thiết
          git add index.html chart_only.png
          
          if ! git diff --staged --quiet; then
            git commit -m "Quick update index: $(TZ='Asia/Ho_Chi_Minh' date +'%Y-%m-%d %H:%M:%S')"
            
            # Kéo code mới nhất từ main về và tự động ưu tiên lấy dữ liệu mới từ bot (ours)
            git pull origin main --no-rebase -X ours -m "Auto merge from bot"
            
            git push origin main
          else
            echo "Không có dữ liệu mới."
          fi
