name: Quick Update Index

concurrency:
  group: github-pages-deploy

on:
  schedule:
    - cron: '0,30 * * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-index:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests pandas beautifulsoup4 plotly user_agent openpyxl kaleido pytz

      - name: Run Scripts
        run: |
          echo "Kích hoạt cập nhật dữ liệu thị trường..."
          python main.py
          python update_index_only.py

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # ĐÃ SỬA: Thêm chart_only.html vào theo dõi
          git add index.html chart_only.png
          
          if ! git diff --staged --quiet; then
            git commit -m "Quick update index: $(TZ='Asia/Ho_Chi_Minh' date +'%Y-%m-%d %H:%M:%S')"
            
            # Khôi phục/xóa các file thừa khác ngoại trừ những file đã được git add
            git checkout -- .
            git clean -fd
            
            git pull origin main --rebase
            git push origin main
          else
            echo "Không có dữ liệu mới."
          fi
