name: Quick Update Index

# CHÈN VÀO ĐÂY: Giúp xếp hàng các lượt chạy deploy, tránh lỗi nghẽn hệ thống
concurrency:
  group: github-pages-deploy
  cancel-in-progress: false
on:
  schedule:
    - cron: '05,35 * * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-index:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v5
        
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: pip install requests pandas beautifulsoup4 plotly user_agent openpyxl kaleido pytz
          
      - name: Run Scripts
        run: |
          echo "Kích hoạt cập nhật dữ liệu thị trường..."
          python main.py

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          if ! git diff --staged --quiet; then
            git commit -m "Quick update index: $(TZ='Asia/Ho_Chi_Minh' date +'%Y-%m-%d %H:%M:%S')"
            
            # Khôi phục/xóa tất cả thay đổi dư thừa còn sót lại để thư mục làm việc hoàn toàn "sạch"
            git checkout -- .
            git clean -fd
            
            git pull origin main --rebase
            git push origin main
          else
            echo "Không có dữ liệu mới."
          fi
