name: Auto Fetch Stock Data

on:
  push:
    branches: [ main ]
  schedule:
    # 1. Chạy mỗi 15 phút, từ phút 15 đến phút 59 của giờ thứ 2 UTC (tức 9h15 - 9h59 sáng giờ VN)
    - cron: '*/15 2 * * 1-5'
    # 2. Chạy mỗi 15 phút, từ giờ thứ 3 đến giờ thứ 7 UTC (tức 10h00 - 14h59 chiều giờ VN)
    - cron: '*/15 3-7 * * 1-5'
    # 3. Chạy đúng vào lúc 8h00 UTC (tức chốt kết quả cuối cùng lúc 15h00 chiều giờ VN)
    - cron: '0 8 * * 1-5'
    
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openpyxl plotly pandas requests user_agent

    - name: Execute Python Script
      run: python main.py

    - name: Commit and Push Webpage
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
        # SỬ DỤNG -A ĐỂ TỰ ĐỘNG THÊM TẤT CẢ FILE THAY ĐỔI / FILE MỚI (BAO GỒM CẢ INDEX.HTML)
        git add -A
        
        # BẮT BUỘC SỬ DỤNG || EXIT 0 HOẶC || ECHO ĐỂ NẾU KHÔNG CÓ THAY ĐỔI THÌ WORKFLOW VẪN BÁO XANH MƯỢT MÀ
        git commit -m "Cập nhật dữ liệu chứng khoán tự động [skip ci]" || exit 0
        
        git push
