name: Auto Fetch Stock Data

on:
  push:
    branches:
      - main
  schedule:
    # 02:15 UTC đến 08:00 UTC (tương đương 09:15 VN đến 15:00 VN)
    # Cron: 'phút giờ ngày_trong_tháng tháng ngày_trong_tuần'
    - cron: '15,30,45 2 * * 1-5'
    - cron: '0,15,30,45 3-7 * * 1-5'
    - cron: '0 8 * * 1-5'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas plotly user_agent openpyxl

      - name: Execute Python Script
        run: |
          python main.py

      - name: Commit and Push Webpage
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Chỉ add file index.html
          git add index.html
          
          # Kiểm tra nếu có thay đổi thì mới commit
          if git diff --staged --quiet; then
            echo "Không có thay đổi mới, bỏ qua commit."
          else
            git commit -m "Cập nhật dữ liệu chứng khoán tự động [skip ci]"
            git push origin main
          fi
